[package]
name = "winit_demo"
version = "0.1.0"
edition = "2024"

[dependencies]
ui = { path = "../ui/", features = ["winit", "metal", "vulkan", "env_logging"] }
env_logger = "0.11.8"
pollster = "0.4.0"
winit = "0.30.11"
bytemuck = "1.23.0"
wgpu = "25.0.2"
