[alias]
run-winit = "run --example winit -F winit,tracing,vulkan,metal"
run-sctk-layer = "run --example sctk-layer -F sctk,tracing,vulkan,metal"
run-sctk-window = "run --example sctk-window  -F sctk,tracing,vulkan,metal"
run-sctk-lock = "run --example sctk-lock -F sctk,tracing,vulkan"
