[package]
name = "learning_winit"
version = "0.1.0"
edition = "2024"

[dependencies]
ui = { path = "../ui/", features = ["winit", "env_logging"] }
env_logger = "0.11.8"
pollster = "0.4.0"
winit = "0.30.11"
bytemuck = "1.23.0"
