[package]
name = "ui"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.0", default-features = false, features = [
  "derive",
] }
env_logger = "0.11.8"
glyphon = "0.9.0"
image = "0.25.6"
pollster = "0.4.0"
tracing = "0.1.41"
wgpu = { version = "25.0.2", default-features = false, features = [
  "wgsl",
  "vulkan",
  "metal",
] }
winit = { version = "0.30.11", default-features = false, optional = true }

[features]
default = []
winit = ["dep:winit"]
